version: "3.8"

services:
  web:
    build: .
    container_name: lulucoin_backend
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DATABASE_URL=sqlite:///db.sqlite3
    command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]

  db:
    image: postgres:15
    container_name: lulucoin_db
    restart: always
    environment:
      POSTGRES_USER: lulucoin_user
      POSTGRES_PASSWORD: lulucoin_pass
      POSTGRES_DB: lulucoin_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
