# Generated by Django 5.1.7 on 2025-03-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalvariables',
            name='num_blocks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lulucoinblock',
            name='index',
            field=models.IntegerField(default=-1),
        ),
    ]
